### ISSUE TITLE
Why is there no data after decompression?

### ISSUE THREAD

**Issue by fuyunmanbu** [skipness/lzstring-dart#9]
！[上传snip20221130_11.png...]()

```
flutter: ----
flutter: 딦ꊜ䱘ﺈ젘แ茏誇이࿶ꁐ汨箣䇍児煲萛鐟צּ䃥洂㖌ᢩ偓륁�Ҏ퐔&䃵팄莔ᢝ健Ӂゕփ鐗௠恩㥀쟮肀ᤀꭩ퐋ḯ倔̠Ⱍ䁦犁ꀙ=騂쟼༏⠉뿐 ‽佀㦊܀跦׃혒꘠搘ϫ꣄\^E᠜鍓ꁽ㥱腯鴁綨⨂䣘ꠃ똁礆Ά騃꿪楨⥚ʆ⨃췹ꨂପ͚⨃묫蠪\^R度�ꨃ㬪ƺ⬧ਂ數숀﨨⨂렺ė馫哂̉쪖:騂䈻訂閭˂樀맪;稃᷊ɛ꓂À؀䜚ƛ樂町k棂Μᬲ阁痉츁뺚Ƀ騀च%꓂ʊ騀퍺́쨀ǉ擂A샚ώ蜈숁䷋ਂ䩪È䓁ûۙ䀊ຸ逆죫㔪䔀Ǟげꀞა֬ꂌƀ먁䴴ᆀ拘쀣ဉ䦨g嘒Č挀恊぀ଚ怙贸䠄쁔Ρ⣁\^[쪀㑥愠ᆕ퀁愓Ѓ筚Ǳ嶄耱䕀ξ谗蠆膍騀ᐓ⯀쀌ઌဏ̫ż灦聺퍀⊦谐௅爝u侮䀌噰逍ᜫ쐁⿨섀寑聻’谤Χ棁繂쀴逎₨Ժࠦ¹촀ꏱ聅–㍐ؽ᠁๴ŠⓁ\^H䚒膠ཇ倇✠Ⰲ龸섀耞ୀᥜꀄ嘷ࠂẌ˗䓁T尝䎿힉찂$섀徊�㬑茇섌ͱ⨣(Ẁ㺟ᠠࢸ싘ȥÐ趓ڄ‐㈦හǝ먁뒝\^G꙰䮠ʩ守狌솖耞沣ᚰޫ᜴˸ꨀ탥â骀ݳᠾ�Ž俭﩮က녔㤀<…>
flutter: null
```

**Comment by fuyunmanbu** [comment]
![Snip20221130_11](https://user-images.githubusercontent.com/16368126/204777767-2c0d6fdb-c40a-41f9-a389-b78973a8cdc1.png)

**Comment by skipness** [comment]
Which version are you using?

**Comment by fuyunmanbu** [comment]
lzstring: ^2.0.0+2

**Comment by fuyunmanbu** [comment]
In this case, UTF16Sync compression and decompression will work normally

**Comment by skipness** [comment]
so `UTF16Sync` solved your issue?

**Comment by fuyunmanbu** [comment]
Yes, but I'm not sure what the problem is and whether it's a perfect solution

**Comment by skipness** [comment]
Can't tell as I have no clue about what is your input, issue close
